### ISSUE TITLE
Plugin is not 7.0 compatible

### ISSUE THREAD

**Issue by VladimirAus** [drupal-code-builder/drupal-code-builder#215]
### Error

On php 7.0 there are number of errors: 

* nullable types were introduced in 7.1: https://www.php.net/manual/en/migration71.new-features.php
* ` ReflectionType::getName()` does not exists.

### Proposal

Update php dependency in composer.json to 7.1+

**Comment by joachim-n** [comment]
Oops.

Thanks for reporting this. I'll update the PHP version in composer.json as you suggest.
