### ISSUE TITLE
Update hook_install for Drupal 8

### ISSUE THREAD

**Issue by jurgenhaas** [drupal-code-builder/drupal-code-builder#231]
According to this change note (https://www.drupal.org/node/3098920) the hook_install now gets a variable `$is_syncing` which is not covered by `Test/sample_hook_definitions/8/module.api.php`. Unfortunately, PhpStorm refers to that definition when helping to insert a new hook into a module and hence you won't get that argument.

**Comment by joachim-n** [comment]
Thanks for the issue report.

I've updated the sample definitions, will make a new release with this fix soon.
