### ISSUE TITLE
hook_help appearing twice.

### ISSUE THREAD

**Issue by kwfinken** [drupal-code-builder/drupal-code-builder#249]
When using this with the module_builder module, if I set a help text or include hook_help, hook_help shows up twice in my .module file.

I am unable to determine if this is an issue with module_builder or this library.  The ticket for the module is: https://www.drupal.org/project/module_builder/issues/3277228.

**Comment by joachim-n** [comment]
It'll be with this package. Thanks for reporting!

**Comment by joachim-n** [comment]
Could you try the 4.2.1 release I've just tagged? I saw a similar bug the other day which is now fixed in that.

**Comment by kwfinken** [comment]
Worked like a charm.  Thank you for the quick response.

**Comment by joachim-n** [comment]
That's great to hear. Thanks for reporting back!
