### ISSUE TITLE
Deprecated function: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated

### ISSUE THREAD

**Issue by alvar0hurtad0** [drupal-code-builder/drupal-code-builder#302]
If the plugin does not define plugin_interface, there's a notice in log.

Even more it lands into an error as ReflectionClass doesn't support NULL as a parameter.

Examples
Drupal\breakpoint\BreakpointManager;
Drupal\Core\Config\TypedConfigManager;

**Comment by alvar0hurtad0** [comment]
This PR is related to this issue:
https://github.com/drupal-code-builder/drupal-code-builder/pull/303

**Comment by joachim-n** [comment]
Thanks!

I think addPluginBaseClass() should probably only be called for Annotation plugins -- will investigate.
