### ISSUE TITLE
Deprecated function: Creation of dynamic property with PHP 8.2

### ISSUE THREAD

**Issue by Peppe87** [drupal-code-builder/drupal-code-builder#308]
As title, with PHP 8.2 there are a couple of errors: 

> Deprecated function: Creation of dynamic property DrupalCodeBuilder\Task\Configuration::$componentClassHandler is deprecated in DrupalCodeBuilder\Task\Configuration->__construct() (line 30 of /var/www/html/vendor/drupal-code-builder/drupal-code-builder/Task/Configuration.php).

> Deprecated function: Creation of dynamic property DrupalCodeBuilder\Task\Collect\DataTypesCollector::$environment is deprecated in DrupalCodeBuilder\Task\Collect\DataTypesCollector->__construct() (line 41 of /var/www/html/vendor/drupal-code-builder/drupal-code-builder/Task/Collect/DataTypesCollector.php).

**Comment by joachim-n** [comment]
Thanks for the report.
I think I've fixed all these - new release soon.
