### ISSUE TITLE
sort class imports

### ISSUE THREAD

**Issue by joachim-n** [drupal-code-builder/drupal-code-builder#53]
Eg:

```
use Drupal\test_module\Plugin\CatFeeder\CatFeederInterface;\n
use Drupal\Core\Cache\CacheBackendInterface;\n
use Drupal\Core\Extension\ModuleHandlerInterface;\n
use Drupal\Core\Plugin\DefaultPluginManager;\n
use Drupal\test_module\Annotation\CatFeeder;\n
```

I generally see:

- Drupal\Component - then alphabetical
- Drupal\Core - then alphabetical
- Drupal\*module* - alphabetical by module
- vendor stuff eg Symfony.

**Comment by joachim-n** [comment]
Thanks for figuring this one out!

> Some later step (haven't found it) must be doing a final replace of %module.

That happens in the Module generator. The replacement of tokens like %module is a really old piece of functionality, which is there because back then most components didn't have knowledge of things from parent components such as the module machine name. But that is now available to them, so we can put this in for class names at least (and consider removing it completely one of these days).

**Comment by joachim-n** [comment]
I made a rough start on this and it's going to be fiddly...

**Comment by joachim-n** [comment]
I've pushed a rough start on this to branch `sandbox-53-import-order`.

Some of the test failures look icky to me.

Particularly:

```
4) DrupalCodeBuilder\Test\Unit\ComponentRouterItem8Test::testRouteGenerationWithMenuLink
MutableTypedData\Exception\InvalidAccessException: Unknown property root_component_name on data at module:router_items:0:controller.
```

ALL components should have the 'root_component_name' property available! I hope this isn't to do with being in a multi-value delta item...

**Comment by joachim-n** [comment]
> ALL components should have the 'root_component_name' property available! I hope this isn't to do with being in a multi-value delta item...

No wait, it's not that. I think it's possible that acquired data only works with components from the user-given data, not from requiredComponents() data. There might be a TODO in the code about that...

**Comment by jedihe** [comment]
I was able to get testRouteControllerTypes() to pass by doing this in RouterItem.php:

```diff
                       '\Drupal\\'
-                      . $component_data->getParent()->root_component_name->value . '\\'
+                      . $component_data->getParent()->getParent()->root_component_name->value . '\\'
                       . $component_data->getParent()->controller_relative_class_name->value . '::content';
```

My best guess is by going up one more step I reached the level of user-given data, for which root_component_name is defined.

**Comment by jedihe** [comment]
I also tried this, but it failed (root_component_name resolves to ''):

```diff
diff --git a/Generator/RouterItem.php b/Generator/RouterItem.php
index e821d4fa..335f059d 100644
--- a/Generator/RouterItem.php
+++ b/Generator/RouterItem.php
@@ -63,6 +63,14 @@ class RouterItem extends BaseGenerator {
           'controller' => VariantDefinition::create()
             ->setLabel('Controller class')
             ->setProperties([
+              'root_component_name' => PropertyDefinition::create('string')
+                ->setInternal(TRUE)
+                ->setAcquiringExpression("getRootComponentName(requester)"),
+              'containing_component' => PropertyDefinition::create('string')
+                ->setInternal(TRUE),
+              'component_base_path' => PropertyDefinition::create('string')
+                ->setInternal(TRUE)
+                ->setAcquiringExpression("requester.component_base_path.value"),
               'controller_relative_class_name' => PropertyDefinition::create('string')
                 ->setInternal(TRUE)
                 ->setDefault(DefaultDefinition::create()
@@ -79,6 +87,8 @@ class RouterItem extends BaseGenerator {
                 ->setDefault(DefaultDefinition::create()
                   ->setCallable(function (DataItem $component_data) {
                     // AARGH HACK! Repeating the work the class component does!
                     return
                       '\Drupal\\'
                       . $component_data->getParent()->root_component_name->value . '\\'
```

**Comment by joachim-n** [comment]
> My best guess is by going up one more step I reached the level of user-given data, for which root_component_name is defined.

Thanks!

Yeah, it's because ComponentCollector only does acquiring data from the requester for user-given data. It should do acquireDataFromRequestingComponent() for data from requestedComponents() too. (Same reason your attempt at defining the properties won't work. Those are actually already there -- everything gets them from BaseComponent.)

But your fix will do as a quick hack!

**Comment by joachim-n** [comment]
I'm working on fixing the failing test in ComponentPHPClassFile8Test.

If you wanted to tinker with this some more, I reckon the test failures in ComponentPluginType8Test should be relatively easy to fix. There'll be something in PHPClass or PHPClassFile that tries to remove classes in the current class's namespace from the class imports, which is now failing because it's expecting '%module'.

**Comment by joachim-n** [comment]
Fixed the ComponentPHPClassFile8Test test, pushed to the branch.

**Comment by jedihe** [comment]
Alright! working now on fixing the ComponentPluginType8Test failures.

**Comment by jedihe** [comment]
Pushed a fix for the unit tests. I'll now add a check to verify the use statements are sorted (or set PHPCS to check for it?).

**Comment by jedihe** [comment]
Alright! #216 now checks that use statements are sorted (case-insensitive). Integration tests are failing, though :disappointed:.

**Comment by joachim-n** [comment]
> Integration tests are failing, though

Don't worry about those. They run locally, and there's a glitch I can't figure out on Travis.

**Comment by jedihe** [comment]
#216 is now updated with the requested changes.

**Comment by joachim-n** [comment]
I've added a more comprehensive test for class imports (and yay for the service container that I added last month -- it's meant I can mock the hook data in this test to get loads of classes into a generated PHP file!)

So we've fixed the problem with '%module' getting sorted wrong, but this issue is also about the fact that Drupal by convention doesn't actually sort the imports strictly alphabetically (sorry, I lost sight of that part of the original bug report when I was suggesting natcasesort!).

The test I added produces this:

```
use Alpha\Flour;\n
use Beta\Eggs;\n
use Drupal\alpha_module\Sugar;\n
use Drupal\beta_module\Almonds;\n
use Drupal\Component\Baking\Yeast;\n
use Drupal\Component\Fruit\DriedApricots;\n
use Drupal\Core\Chocolate\Dark;\n
use Drupal\Core\Spices\Cinammon;\n
```

and it should have:

```
use Drupal\Component\Baking\Yeast;\n
use Drupal\Component\Fruit\DriedApricots;\n
use Drupal\Core\Chocolate\Dark;\n
use Drupal\Core\Spices\Cinammon;\n
use Drupal\alpha_module\Sugar;\n
use Drupal\beta_module\Almonds;\n
```

with Drupal classes in the order components, then core, then modules.

I thought that vendor classes were getting put at the end, but grepping core code I see that things like Behat and Composer imported classes get put before Drupal, so the top-level namespace is alphabetical. Although those are all in tests, and none of those files have module classes getting imported.

It looks like just removing the case-insensitivity will do the trick here?

**Comment by joachim-n** [comment]
I pushed a change to use just sort(). The order is now:

```
use Alpha\Flour;\n
use Beta\Eggs;\n
use Drupal\Component\Baking\Yeast;\n
use Drupal\Component\Fruit\DriedApricots;\n
use Drupal\Core\Chocolate\Dark;\n
use Drupal\Core\Spices\Cinammon;\n
use Drupal\alpha_module\Sugar;\n
use Drupal\beta_module\Almonds;\n
use Mu\Marzipan;\n
use Zeta\Pistachios;\n
```

which matches what I see in core files.

I think this is now done? Let me know what you think.

**Comment by jedihe** [comment]
Alright! the case-sensitive ordering matches most of the cases I checked in core, so it's perfect.

I guess there is a little bit of inconsistency (see core/modules/node/src/NodeTranslationHandler.php) just because this is not enforced by the phpcs sniffs.

**Comment by joachim-n** [comment]
Thanks for all your help with this!
