### ISSUE TITLE
generating a plugin of a type that's configurable should write a sample config YML

### ISSUE THREAD

**Issue by joachim-n** [drupal-code-builder/drupal-code-builder#54]
If a plugin's interface extends ConfigurablePluginInterface then there should be a config yml.

**Comment by joachim-n** [comment]
I don't see where the relationship between the plugin type and the config key prefix is defined. 

Eg, 

```
field.formatter.settings.*:
```

**Comment by petebarnett** [comment]
There isn't a hard relationship between the plugin type and the config key, other than the fact that a configuration entity type implementing `EntityWithPluginCollectionInterface` usually exists which has a plugin collection loading plugins of that type.
So _that_ defines the config key as per its entity annotation `config_prefix` property.

I guess the link could be established from an entity type to its plugins, but (surely) it's not necessarily a one-to-one mapping, as there's nothing stopping two config entities having plugin managers using the same plugin type.

Not sure how much that helps, but it's what I know!

**Comment by joachim-n** [comment]
Thanks!

Something that maybe Plugin module should provide to fill in the gap...

In the meantime, I think this could be figured out with code analysis: 

1. we know the module that defines the plugin type
2. if this has its own plugins of this type, look in the module's config schema for any config definitions whose IDs end in the plugin names. 
3. If we find matches, e.g. prefix.plugin_a, prefix.plugin_b, then we can fairly safely say 'prefix' is the right config key prefix.

**Comment by joachim-n** [comment]
Fixed.
